option(ENABLE_CPPCHECK "Enable static analysis with cppcheck" OFF)
if(ENABLE_CPPCHECK)
  find_program(CPPCHECK_COMMAND NAMES cppcheck)
  if(CPPCHECK_COMMAND)
    set(CMAKE_CXX_CPPCHECK ${CPPCHECK} --suppress=missingInclude --enable=all --inconclusive)
    message(STATUS "Found ${CPPCHECK_COMMAND}")
  else()
    message(SEND_ERROR "cppcheck requested but executable not found")
  endif()
endif()

option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" OFF)
if(ENABLE_CLANG_TIDY)
  find_program(CLANGTIDY_COMMAND NAMES clang-tidy clang-tidy-10)
  if(CLANGTIDY_COMMAND)
    set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY_COMMAND} -fix -extra-arg=-Wno-unknown-warning-option)
    message(STATUS "Found ${CLANGTIDY_COMMAND}")
  else()
    message(SEND_ERROR "clang-tidy requested but executable not found")
  endif()
endif()

option(ENABLE_IWYU "Enable include-what-you-use" OFF)
if(ENABLE_IWYU)
  find_program(IWYU_COMMAND include-what-you-use)
  if(IWYU_COMMAND)
    set(CMAKE_CXX_INCLUDE_WHAT_YOU_USE ${IWYU_COMMAND})
    message(STATUS "Found ${IWYU_COMMAND}")
  else()
    message(SEND_ERROR "include-what-you-use requested but executable not found")
  endif()
endif()
