if(CMAKE_BUILD_TYPE STREQUAL Release)
	find_program(CLANGTIDY_COMMAND NAMES clang-tidy clang-tidy-9 clang-tidy-10)
	if(CLANGTIDY_COMMAND)
		set(DO_CMAKE_CXX_CLANG_TIDY ${CLANGTIDY_COMMAND} -extra-arg=-Wno-unknown-warning-option -warnings-as-errors=* --header-filter=.*)
		message(STATUS "Found ${CLANGTIDY_COMMAND}")
	else()
		message(WARNING "clang-tidy not found")
	endif()
endif()

macro(add_lint project_name)
	if(CLANGTIDY_COMMAND AND CMAKE_BUILD_TYPE STREQUAL "Release" AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
		message(STATUS "Using clang-tidy on ${project_name}")
		set_target_properties(${project_name} PROPERTIES CXX_CLANG_TIDY "${DO_CMAKE_CXX_CLANG_TIDY}")
	endif()
endmacro()
