language: cpp
dist: bionic
os: linux
cache: ccache

before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update

install:
  - pip install --user conan cmake
  - sudo apt-get -y install g++-9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - sudo rm -rf /usr/local/clang-*
  - sudo apt install clang-10 clang-tidy-10 clang-format-10 libfuzzer-10-dev
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 99 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-10 --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-10 --slave /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-10

before_script:
  - ln -s build/compile_commands.json .
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan --version
  - cmake --version
  - gcc --version
  - g++ --version
  - clang --version
  - clang++ --version
  - clang-tidy --version
  - clang-format --version

script:
  - cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DENABLE_CCACHE:BOOL=OFF
  - cmake --build build -- -j2 VERBOSE=1
  - cmake --build build --target test
