apiVersion: v1
kind: ReplicationController
metadata:
  name: hostname-rc
  labels:
    app: hostname-rc-label
    tier: dev
spec:
  replicas: 3
  selector:
    app: hostname-app-label
  template:
    metadata:
      name: hostname-pod
      labels:
        app: hostname-app-label
    spec:
      containers:
      - name: hostname-container-name
        image: 192.168.0.13:5000/skelix/hostname-app:1
        ports:
        - containerPort: 9001
